#ifndef HV_PREPROCESSOR_SUBSTITUTIONS_H
#define HV_PREPROCESSOR_SUBSTITUTIONS_H

// macro to concatenate 2 token sequences.
// need 1 pair for horizontal and 1 pair for vertical.
#define CONCAT_H(A,B) CONCAT_H_HELPER(A,B)
#define CONCAT_H_HELPER(A,B) A##B
#define CONCAT_V(A,B) CONCAT_V_HELPER(A,B)
#define CONCAT_V_HELPER(A,B) A##B

// vertical substitution macros
#define MAX_VERTICAL_SUBSTITUTIONS 10

#define SUBSTITUTE_VERTICALLY_1 V_SUBSTITUTION_STRING(0) 
#define SUBSTITUTE_VERTICALLY_2 SUBSTITUTE_VERTICALLY_1 V_SUBSTITUTION_STRING(1) 
#define SUBSTITUTE_VERTICALLY_3 SUBSTITUTE_VERTICALLY_2 V_SUBSTITUTION_STRING(2) 
#define SUBSTITUTE_VERTICALLY_4 SUBSTITUTE_VERTICALLY_3 V_SUBSTITUTION_STRING(3) 
#define SUBSTITUTE_VERTICALLY_5 SUBSTITUTE_VERTICALLY_4 V_SUBSTITUTION_STRING(4) 
#define SUBSTITUTE_VERTICALLY_6 SUBSTITUTE_VERTICALLY_5 V_SUBSTITUTION_STRING(5) 
#define SUBSTITUTE_VERTICALLY_7 SUBSTITUTE_VERTICALLY_6 V_SUBSTITUTION_STRING(6) 
#define SUBSTITUTE_VERTICALLY_8 SUBSTITUTE_VERTICALLY_7 V_SUBSTITUTION_STRING(7) 
#define SUBSTITUTE_VERTICALLY_9 SUBSTITUTE_VERTICALLY_8 V_SUBSTITUTION_STRING(8)
#define SUBSTITUTE_VERTICALLY_10 SUBSTITUTE_VERTICALLY_9 V_SUBSTITUTION_STRING(9)

#define SUBSTITUTE_VERTICALLY(n) CONCAT_V(SUBSTITUTE_VERTICALLY_,n)

// horizontal substitution macros
#define MAX_HORIZONTAL_SUBSTITUTIONS 10

#define SUBSTITUTE_HORIZONTALLY_1(horizontal) H_SUBSTITUTION_STRING(0,horizontal) 
#define SUBSTITUTE_HORIZONTALLY_2(horizontal) SUBSTITUTE_HORIZONTALLY_1(horizontal) H_SUBSTITUTION_STRING(1,horizontal) 
#define SUBSTITUTE_HORIZONTALLY_3(horizontal) SUBSTITUTE_HORIZONTALLY_2(horizontal) H_SUBSTITUTION_STRING(2,horizontal) 
#define SUBSTITUTE_HORIZONTALLY_4(horizontal) SUBSTITUTE_HORIZONTALLY_3(horizontal) H_SUBSTITUTION_STRING(3,horizontal) 
#define SUBSTITUTE_HORIZONTALLY_5(horizontal) SUBSTITUTE_HORIZONTALLY_4(horizontal) H_SUBSTITUTION_STRING(4,horizontal) 
#define SUBSTITUTE_HORIZONTALLY_6(horizontal) SUBSTITUTE_HORIZONTALLY_5(horizontal) H_SUBSTITUTION_STRING(5,horizontal) 
#define SUBSTITUTE_HORIZONTALLY_7(horizontal) SUBSTITUTE_HORIZONTALLY_6(horizontal) H_SUBSTITUTION_STRING(6,horizontal) 
#define SUBSTITUTE_HORIZONTALLY_8(horizontal) SUBSTITUTE_HORIZONTALLY_7(horizontal) H_SUBSTITUTION_STRING(7,horizontal) 
#define SUBSTITUTE_HORIZONTALLY_9(horizontal) SUBSTITUTE_HORIZONTALLY_8(horizontal) H_SUBSTITUTION_STRING(8,horizontal)
#define SUBSTITUTE_HORIZONTALLY_10(horizontal) SUBSTITUTE_HORIZONTALLY_9(horizontal) H_SUBSTITUTION_STRING(9,horizontal)

#define SUBSTITUTE_HORIZONTALLY(n) CONCAT_H(SUBSTITUTE_HORIZONTALLY_,n)


#endif // HV_PREPROCESSOR_SUBSTITUTIONS_H
